version: '3.9'
services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes:
      - mongo_db:/data/db

  api:
    container_name: api_container
    build: .
    ports:
      - 3030:3030
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo_db
    env_file:
      - .env

volumes:
  mongo_db: {}